id: pipniapi
long_id: com.mokiat.pipniapi
name: PipniAPI
version: 0.1.0
description: REST client application
contact: Momchil Atanasov <momchil.dev@gmail.com>
main: ./cmd/PipniAPI
icon: resources/images/icon.png
copyright: Copyright © 2023, Momchil Atanasov. All rights reserved.
