name: Distribution

on:
  push:
    branches: ["*"] # FIXME master

jobs:
  dist_linux:
    name: Distribution - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: "1.21"

      - name: Install Lacking CLI
        run: go install github.com/mokiat/lacking-cli/cmd/lacking@v0.1.1

      - name: Install Linux Packages
        run: sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Build
        run: lacking dist linux ./

      - name: Linux Distribution
        uses: actions/upload-artifact@v3
        with:
          name: Distribution
          path: ./dist

  dist_macos:
    name: Distribution - MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: "1.21"

      - name: Install Lacking CLI
        run: go install github.com/mokiat/lacking-cli/cmd/lacking@v0.1.1

      - name: Build MacOS
        run: lacking dist macos ./

      - name: MacOS Distribution
        uses: actions/upload-artifact@v3
        with:
          name: Distribution
          path: ./dist
