name: Distribution

on:
  push:
    branches: [master]

jobs:
  compile:
    name: Compile
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            ext: '.exe'
          - os: ubuntu-latest
            ext: ''
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: "1.21"

      - name: Install Lacking CLI
        run: go install github.com/mokiat/lacking-cli/cmd/lacking@v0.1.1

      - name: Install Linux Packages
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Prepare Target Dir
        run: mkdir -p target

      - name: Build MacOS
        if: matrix.os == 'macos-latest'
        run: |
          lacking dist macos ./
          cd dist/macos
          zip -r 'PipniAPI.zip' 'PipniAPI.app'
          cd -
          mv dist/macos/PipniAPI.zip target/

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          lacking dist linux ./
          mv dist/linux/*.deb target/

      - name: Archive Distribution
        uses: actions/upload-artifact@v3
        with:
          name: Distribution
          path: ./target
